POST HTTP://localhost:3001/api/questions
Content-Type: application/json

{
  "question": "Qual é a cor do cavalo branco de Napoleão?",
  "theme": "ATUALIZADO", 
  "options": ["Azul", "Amarelo", "Preto", "Branco", "Marrom"],
  "answer": "Branco",
  "level": "Facil",
  "image": "https://www.infoescola.com/wp-content/uploads/2012/07/napoleao-bonaparte.jpg"
}

###

GET HTTP://localhost:3001/api/questions

###

GET HTTP://localhost:3001/api/questions/6519dae82b6488185349538a

###

DELETE HTTP://localhost:3001/api/questions/6519dae82b6488185349538a

###

PUT HTTP://localhost:3001/api/questions/6519dae82b6488185349538a
Content-Type: application/json

{
  "question": "Qual é a cor do cavalo branco de Napoleão?",
  "theme": "Conhecimentos gerais", 
  "options": ["Azul", "Amarelo", "Preto", "Branco", "Marrom"],
  "answer": "Branco",
  "level": "Facil",
  "image": "https://www.infoescola.com/wp-content/uploads/2012/07/napoleao-bonaparte.jpg"
}

###